version: 1.0.{build}
configuration: Release
nuget:
  account_feed: true
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: src\MiNET\MiNET.Service\bin\Release
  name: ranet-bin
- path: src/MiNET/MiNET.Service/\**\*.nupkg
